databaseFile: wasteland.sqlite3

chat:
  # `{enlisted}`, `{officer}`, `{console}`, and `{rank}` indicate the rank prefix
  # using the highest enlisted, officer, console, and overall ranks respectively.
  #
  # `{towny}` indicates the town prefix if the player is in a town and the town tag is set.
  #
  # The first `%s` is the player's name and the second is the message itself.
  formats:
    # The format used for chat.
    chat: "{towny}{enlisted}%s: %s"
    # The format used for chat player with the `wasteland.chat.officer` permission.
    officer: "{towny}{officer}%s: %s"
    # The format used for `/official` when used by a player.
    official: "{officer}%s: %s"
    # The format used for `/official` when used by the server.
    console: "{console_full}§r: %s"
  prefixes:
    # `{abbr}` is the rank's abbreviation, with formatting
    rank: "§r[{abbr}§r] "
    # `{tag}` is the town's tag
    towny: "§r[§9{tag}§r] "

#
# enlisted:
#   decoration: <ColorCode>    # optional
#   description: <description> # optional, may reference the rank's number of `{kills}`.
#   ranks:
#     <rankID>: # the rank permission will be `wasteland.rank.<rankID>`.
#       name: <full rank name>            # optional, defaults to the rank ID
#       abbreviation: <rank abbreviation> # optional, defaults to the name
#       description: <rank description>   # optional, defaults to `enlisted.description`.
#       succeeds: <rankID>                # optional, the prior rank (defaults to nothing)
#       preferred: <rankID>               # optional, used to disambiguate multiple ranks
#                                         #           which both succeed the same rank.
#                                         #           If there is only one successor, it defaults to that.
#       color: <ColorCode>                # optional
#       decoration: <ColorCode>           # optional, defaults to `enlisted.decoration`
#       kills: <0+>                       # optional, but the rank won't be automatically used without it
#    ...
#
# You *must* set a default enlisted rank by setting the rank's kills to 0; the plugin will break if you don't.
# Setting multiple default ranks is undefined behavior.
# It may be possible for a player to have no rank in the future, but it is not for now.
#
# Players will automatically be promoted to their preferred rank if they have enough kills for it.
# If there are ambiguous ranks, then:
# * If the player has permission `wasteland.prefer-rank.<rankId>`, then they will be promoted to their preferred rank.
# * If one of the next ranks is `preferred`, then they will be promoted to that rank.
# * Otherwise, they will *not* be promoted until a `prefer-rank` permission is set.
#
# Setting a player's preferred rank will retroactively update their rank to that rank
# (e.g. if a player is MGySgt and you set `wasteland.prefer-rank.fstsgt`, they will become SgtMaj),
# but only when the plugin's configuration (or the whole plugin) is reloaded.
#
# It is also possible to set a player's rank to a rank they do not have the kills for,
# by using the `wasteland.rank.<rankID>` permission.
#

# The default ranks are based on those of the U.S. marines.
# The default colors are based on Terraria's rarity scheme (https://terraria.gamepedia.com/Rarity).

# You may wish to remove the unused alternative ranks.

enlisted:
  description: "{kills} kills."
  ranks:
    # A default rank which is not part of the marines.
    fodder:
      # `name` is optional and defaults to the `title`.
      name: Zombie Fodder
      # `abbreviation` is optional and defaults to the rank ID.
      abbreviation: Fodder
      description: This person probably won't survive long.
      color: GRAY
      kills: 0
    pvt:
      name: Private
      abbreviation: Pvt
      succeeds: fodder
      color: WHITE
      kills: 100
    pfc:
      name: Private First Class
      abbreviation: PFC
      succeeds: pvt
      color: BLUE
      kills: 250
    lcpl:
      name: Lieutenant Corporal
      abbreviation: LCpl
      succeeds: pfc
      color: GREEN
      kills: 500
    cpl:
      name: Corporal
      abbreviation: Cpl
      succeeds: lcpl
      color: RED
      kills: 1000
    sgt:
      name: Sergeant
      abbreviation: Sgt
      succeeds: cpl
      color: LIGHT_PURPLE
      kills: 2500
    ssgt:
      name: Staff Sergeant
      abbreviation: SSgt
      succeeds: sgt
      color: YELLOW
      kills: 5000
    gysgt:
      name: Gunnery Sergeant
      abbreviation: GySgt
      succeeds: ssgt
      preferred: msgt
      color: AQUA
      kills: 10000
    # Alternative DARK_RED rank.
    fstsgt:
      name: First Sergeant
      abbreviation: 1stSgt
      description: "{kills} kills. Alternative rank to GySgt."
      succeeds: gysgt
      color: DARK_RED
      kills: 25000
    msgt:
      name: Master Sergeant
      abbreviation: MSgt
      succeeds: gysgt
      color: DARK_RED
      kills: 25000
    # Alternative DARK_PURPLE rank.
    sgtmaj:
      name: Sergeant Major
      abbreviation: SgtMaj
      description: A survivor of the wasteland, with over {kills} kills. Alternative rank to MSgt, promoted from 1stSgt.
      succeeds: fstsgt
      color: DARK_PURPLE
      kills: 50000
    mgysgt:
      name: Master Gunnery Sergeant
      abbreviation: MGySgt
      description: A survivor of the wasteland, with over {kills} kills.
      succeeds: msgt
      color: DARK_PURPLE
      kills: 50000

# Officer ranks cannot be obtained by killing zombies;
# they must manually be set using permissions.
# Setting permissions for any rank also gives permissions for all previous ranks.
# You may also optionally specify a rank `description`,
# which will be listed to describe what a staff member of that rank does,
# or what a donor of that rank donated.

# It may be best to remove ranks that you are not using to avoid cluttering the ranks list.

officer:
  decoration: BOLD
  # The rank used by the console when it makes an official message.
  # This *must* be specified or the plugin will break.
  console: gas
  ranks:
    sndlt:
      name: Second Lieutenant
      abbreviation: 2ndLt
      color: WHITE
    fstlt:
      name: First Lieutenant
      abbreviation: 1stLt
      succeeds: sndlt
      color: BLUE
    capt:
      name: Captain
      abbreviation: Capt
      succeeds: fstlt
      color: GREEN
    maj:
      name: Major
      abbreviation: Maj
      succeeds: capt
      color: RED
    ltcol:
      name: Lieutenant Colonel
      abbreviation: LtCol
      succeeds: maj
      color: LIGHT_PURPLE
    col:
      name: Colonel
      abbreviation: Col
      succeeds: ltcol
      color: YELLOW
    bgen:
      name: Brigadier General
      abbreviation: BGen
      succeeds: col
      color: AQUA
    majgen:
      name: Major General
      abbreviation: MajGen
      succeeds: bgen
      color: DARK_RED
    ltgen:
      name: Lieutenant General
      abbreviation: LtGen
      succeeds: majgen
      color: DARK_PURPLE
    gen:
      name: General
      abbreviation: Gen
      succeeds: ltgen
      color: GOLD
    gas:
      name: General of the Armies
      abbreviation: GAS
      description: The server console.
      color: GOLD

kills:
  # The eligible monsters are the entity types which, if killed, will count towards your next promotion.
  # Each value must be a valid Bukkit EntityType (e.g. `WITHER_SKELETON` or `ENDERMAN`),
  # or one of these built-in entitiy collections:
  # * `bosses`: The ender dragon or wither.
  # * `hostiles`: Mobs which will attack you on sight, including the bosses.
  # * `neutrals`: Mobs which will only attack you under certain conditions,
  #               e.g. wolves attack you if attacked, enderman attack you if looked at, spiders attack in the dark.
  # * `monsters`: Mobs which are eligiable for the "Monster Hunter" achievement,
  #               which is to say all of the hostile mobs, endermen, spiders, and zombified piglins.
  # * `zombies`: All zombies, including zombified piglins.
  # * `spiders`: All spiders: regular spiders and cave spiders.
  #
  # The wiki lists which mobs are bosses, hostile, or neutral: https://minecraft.gamepedia.com/Mob#List_of_mobs
  # Monsters are defined as the mobs which are eligible for the Monster Hunter achievement
  # (all hostile mobs plus endermen, spiders, and zombified piglins).
  eligible:
    # You must give a name for messages to the player, for e.g. "You must kill X more ??? before your next promotion."
    name: monsters
    entities: [bosses, monsters]

#
# spawns:
#   # Valid monster types are are CREEPER, SKELETON, SPIDER, and ZOMBIE.
#   # The numbers generated by this section's configuration are multiplied together
#   # to determine the probability of a monster spawning at a specific location,
#   # and the amount by which a monster succeeds its probability check
#   # count towards its spawn quality for the purpose of applying buffs.
#   <MonsterType>: 
#     # The light levels in which a monster can spawn.
#     # The probability of a monster spawning is determined by how much light is on the desired spawn block,
#     # reaching a probability of 0.0 when the light reaches the specified maximum.
#     light:
#       maximum: <integer> # defaults to 9
#       
#       # A block's light level is the maximum of the block light and the sunlight and moonlight added together.
#       # The weights affect how much each kind of light contributes toward the overall light level:
#       # Before calculating the overall light level, each light source is multiplied by its respective weight.
#       # The sun and block light level weights default to 1; the moon light level weight defaults to 0.
#       #
#       # A negative weight means that light from this source will *increase* the probability of a monster spawning
#       # in a given light, including in brighter areas (so if you had `moon: -1.0`, on a full moon,
#       # monsters would be able to spawn in block light levels up to `9 + 6`, whereas with `1.0` it would be `9 - 6`).
#       #
#       # Unlike in Vanilla, the sunlight level doesn't go directly between 15 and 0 at dawn and dusk.
#       # There is a *gradual transition* between sunlight and moonlight for the duration of dawn and dusk,
#       # and in vanilla, moonlight doesn't exist at all so that's a new thing too.
#       #
#       # Finally, sky light levels aren't calculated in quite the same way as block light levels.
#       # Rather than diminishing one light level per block, the light diminishes by `1/15th` of its maximum per block.
#       # This means that moonlight shines dramatically deeper into caves and buildings, albeit only at low intensity.
#       #
#       # Moonlight by phase of moon:
#       # * FULL:            6
#       # * WANING_GIBBOUS:  5
#       # * THIRD_QUARTER:   3
#       # * NEW:             0
#       # * WAXING_CRESCENT: 2
#       # * FIRST_QUARTER:   3
#       # * WAXING_GIBBOUS:  4
#       #
#       # There isn't any particular reason for the moon phase light to be asymmetrical, and the numbers are arbitrary;
#       # I made them asymmetrical to make things interesting, and the numbers were chosen just because they felt right.
#       # Perhaps I will make the moonlight by phase configurable in the future.
#       #
#       weights:
#         sun: <float>
#         moon: <float>
#         block: <float>
#
#     # The y-levels within which a monster can spawn.
#     # Like with light, the probability of a monster spawning is diminished the farther it is from the center of the region.
#     height:
#       minimum: <integer> # Defaults to 0
#       maximum: <integer> # Defaults to the largest possible integer. `-1` will *not* work here!
#
#     # The probability of spawning will be multiplied by the modifier specified here depending on what moon phase it is.
#     # The moon phase multiplier *only* has effect between dusk and dawn, although it *does* have effect underground.
#     phases:
#       <MOON_PHASE>: <float>
#       ...
#   ...
#

spawns:
   CREEPER:
      # double spawns in the first and third quarter
      phases:
         THIRD_QUARTER: 2.0
         FIRST_QUARTER: 2.0
      # only spawn below 50 blocks, the lower the more frequent
      height:
         maximum: 50
   SKELETON:
      phases:
         THIRD_QUARTER: 2.0
         FIRST_QUARTER: 2.0
      # only spawn above 80 blocks, the higher the more frequent
      height:
         minimum: 80
   SPIDER:
      light:
          maximum: 5
          weights:
            # spawn up to light level 1
            sun: 4.3
            # spawn up to light level 3
            moon:  1.5
            # spawn up to light level 4
            block: 1.2
      # very strongly prefers dark moon phases
      phases:
          NEW: 3.0
          WANING_GIBBOUS: 1.5
          WAXING_GIBBOUS: 1.5
          THIRD_QUARTER: 0.5
          FIRST_QUARTER: 0.5
          FULL: 0.3
   ZOMBIE:
      light:
         weights:
            # Zombies are only affected by the sky light level a quarter as much,
            # meaning they can still sometimes spawn in broad daylight.
            # They also slightly benefit from moonlight.
           sun: 0.25
           moon: -0.2
      phases:
         FULL: 2.0
         WAXING_GIBBOUS: 1.5
         WANING_GIBBOUS: 1.5
         NEW: 0.5
         
kit:
  # How long a player has to wait between kits, in ticks.
  # The default is five minutes.
  period: 6000
  # A random durability will be chosen per tool depending on how many kits the player has received.
  # The tool will not be dropped if the durability chosen is less than one eight of the item's max.
  tools:
  - GOLDEN_SWORD
  - GOLDEN_PICKAXE
  - GOLDEN_SHOVEL
  - GOLDEN_AXE
  - GOLDEN_HOE
  # A random quantity will be chosen depending on how many kits the player has received.
  # The item type will not be dropped if the quantity chosen is less than one eighth of the maximum.
  items:
    ROTTEN_FLESH: 32
   