name: Wasteland
author: HuskFodder
main: me.jamestmartin.wasteland.Wasteland
version: 0.1.0
api-version: 1.16

softdepend: [Towny]

commands:
   rank:
      description: View your rank and how many monsters you have killed.
      usage: "Usage: /<command> [<player>]"
      permission: wasteland.view-rank
      permission-message: You do not have permission to view your rank.
   rankeligiblemobs:
      description: View a list of monsters which you can kill to get promoted.
      usage: "Usage: /<command>"
      permission: wasteland.view-eligible-mobs
      permission-message: You cannot view the list of promotion-eligible monsters.
   ranks:
      description: List the server ranks.
      usage: "Usage: /<command>"
   setkills:
      description: Set another player's number of kills for debugging.
      usage: "Usage: /<command> [<player>] <kills>"
      permission: wasteland.kills.set
      permission-message: You do not have permission to set anyone's kills.
   official:
      description: Make an official announcement using your staff rank.
      usage: "Usage: /<command> <message>"
      permission: wasteland.official
      permission-message: You are not a staff member with an officer rank.

   # debug commands
   debugspawnweights:
      description: View the monster spawn weights at the block you are looking at.
      usage: "Usage: /<command>"
      permission: wasteland.debug.spawns.weights
      permission-message: You do not have permission to view spawn debug information.

permissions:
   wasteland.chat.officer:
      description: Show a player's officer rank even in normal chat.
      default: false

   wasteland.view-rank:
      description: Allows you to view your /rank.
      default: true
   wasteland.view-rank.kills:
      description: Allows you to see how many kills you have using /rank.
      default: true
      children:
         wasteland.view-rank: true
   wasteland.view-rank.other:
      description: Allows you to see someone else's /rank.
      default: true
      children:
         wasteland.view-rank: true
   wasteland.view-rank.other.kills:
      description: Allows you to see how many kills someone else has using /rank.
      default: false
      children:
         wasteland.view-rank.kills: true
         wasteland.view-rank.other: true

   wasteland.kills.set:
      description: Allows you to set player kills using /setkills.
      default: op
      children:
         wasteland.view-rank.other.kills: true
         
   wasteland.view-eligible-mobs:
      description: Allows you to see the specific list of what mobs count towards promotion with /rankeligiblemobs.
      default: true

   wasteland.debug:
      description: Wasteland plugin debug commands.
      default: false
      children:
         wasteland.debug.spawns: true
   wasteland.debug.spawns:
      description: Commands for debugging the spawning system.
      default: false
      children:
         wasteland.debug.spawns.weights: true
   wasteland.debug.spawns.weights:
      description: Allows you to see the spawn weights by mob type at a block.
      default: false
