name: Wasteland
author: jtmar
main: me.jtmar.wasteland.Wasteland
version: 0.0.0
api-version: 1.12

softdepend: [Towny]

commands:
   rank:
      description: View your rank and how many monsters you have killed.
      usage: "Usage: /<command> [player]"
      aliases: [zkills, kills]
      permission: wasteland.kills
      permission-message: You do not have permission to view your own kills.
   ranks:
      description: List the server ranks.
      usage: "Usage: /<command>"
   setkills:
      description: Set another player's number of kills for debugging.
      usage: "Usage: /<command> [player] kills"
      permission: wasteland.kills.set
      permission-message: You do not have permission to set anyone's kills.
   official:
      description: Make an official announcement using your staff rank.
      usage: "Usage: /<command> [message]"
      permission: wasteland.official
      permission-message: You are not a staff member.

permissions:
   wasteland.kills:
      description: Allows you to view your /kills.
      default: true
   wasteland.kills.other:
      description: Allows you to view another player's /kills.
      default: op
      children:
         wasteland.kills: true
   wasteland.kills.set:
      description: Allows you to set player kills using /setkills.
      default: op
      children:
         wasteland.kills.other: true
   
# Kill ranks      
   
   wasteland.rank.fodder:
      default: true
   wasteland.rank.pvt:
      default: false
      children:
         wasteland.rank.fodder: true
   wasteland.rank.pfc:
      default: false
      children:
         wasteland.rank.pvt: true
   wasteland.rank.lcpl:
      default: false
      children:
         wasteland.rank.pfc: true
   wasteland.rank.cpl:
      default: false
      children:
         wasteland.rank.lcpl: true
   wasteland.rank.sgt:
      default: false
      children:
         wasteland.rank.cpl: true
   wasteland.rank.ssgt:
      default: false
      children:
         wasteland.rank.sgt: true
   wasteland.rank.gysgt:
      default: false
      children:
         wasteland.rank.ssgt: true
   wasteland.rank.msgt:
      default: false
      children:
         wasteland.rank.gysgt: true
   wasteland.rank.mgysgt:
      default: false
      children:
         wasteland.rank.msgt: true

# Staff ranks

   wasteland.official:
      default: ops
   wasteland.rank.2ndlt:
      default: false
      children:
         wasteland.official: true
   wasteland.rank.1stlt:
      default: false
      children:
         wasteland.rank.2ndlt: true
   wasteland.rank.capt:
      default: false
      children:
         wasteland.rank.1stlt: true
   wasteland.rank.maj:
      default: false
      children:
         wasteland.rank.capt: true
   wasteland.rank.ltcol:
      default: false
      children:
         wasteland.rank.maj: true
   wasteland.rank.col:
      default: false
      children:
         wasteland.rank.ltcol: true
   wasteland.rank.bgen:
      default: false
      children:
         wasteland.rank.col: true
   wasteland.rank.majgen:
      default: false
      children:
         wasteland.rank.bgen: true
   wasteland.rank.ltgen:
      default: false
      children:
         wasteland.rank.majgen: true
   wasteland.rank.gen:
      default: false
      children:
         wasteland.rank.ltgen: true