name: Wasteland
author: HuskFodder
main: me.jtmar.wasteland.Wasteland
version: 0.0.0
api-version: 1.14

softdepend: [Towny]

commands:
   rank:
      description: View your rank and how many monsters you have killed.
      usage: "Usage: /rank [<player>]"
      permission: wasteland.view-rank
      permission-message: You do not have permission to view your rank.
   ranks:
      description: List the server ranks.
      usage: "Usage: /<command>"
   setkills:
      description: Set another player's number of kills for debugging.
      usage: "Usage: /<command> [player] kills"
      permission: wasteland.kills.set
      permission-message: You do not have permission to set anyone's kills.
   official:
      description: Make an official announcement using your staff rank.
      usage: "Usage: /<command> [message]"
      permission: wasteland.official
      permission-message: You are not a staff member.

permissions:
   wasteland.chat.officer:
      description: Show a player's officer rank even in normal chat.
      default: false

   wasteland.view-rank:
      description: Allows you to view your /rank.
      default: true
   wasteland.view-rank.kills:
      description: Allows you to see how many kills you have using /rank.
      default: true
      children:
         wasteland.view-rank: true
   wasteland.view-rank.other:
      description: Allows you to see someone else's /rank.
      default: true
      children:
         wasteland.view-rank: true
   wasteland.view-rank.other.kills:
      description: Allows you to see how many kills someone else has using /rank.
      default: false
      children:
         wasteland.view-rank.kills: true
         wasteland.view-rank.other: true

   wasteland.kills.set:
      description: Allows you to set player kills using /setkills.
      default: op
      children:
         wasteland.view-rank.other.kills: true